name: Build, Test, Publish & Deploy

trigger:
- main

pool:
  vmImage: 'windows-2022'

variables:
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - group: Auth0
  - group: WebApi

steps:
- task: NuGetToolInstaller@1
  displayName: "Install NuGet"

- task: NuGetCommand@2
  displayName: "Restore packages"
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: "Build solution"
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: FileTransform@1
  displayName: "Transform json for Albelli.Assessment.WebApi"
  inputs:
    folderPath: 'Albelli.Assessment.WebApi\bin\$(BuildConfiguration)\net6.0\'
    fileType: 'json'
    targetFiles: 'appsettings.json'

- task: FileTransform@1
  displayName: "Transform json for Albelli.Assessment.WebApi.IntegrationTests"
  inputs:
    folderPath: 'Albelli.Assessment.WebApi.IntegrationTests\bin\$(BuildConfiguration)\net6.0\'
    fileType: 'json'
    targetFiles: 'appsettings.json'

- task: VSTest@2
  displayName: "Run xUnit tests"
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\bin\$(BuildConfiguration)\**\Albelli.Assessment.Core.Tests.dll
      !**\obj\**
      !**\ref\**
      !**\xunit.runner.visualstudio.testadapter.dll
      !**\xunit.runner.visualstudio.dotnetcore.testadapter.dll
    searchFolder: '$(System.DefaultWorkingDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Publish and zip'
  inputs:
    command: publish
    publishWebProjects: false
    projects: Albelli.Assessment.WebApi\Albelli.Assessment.WebApi.csproj
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure Web App'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: $(SubscriptionId)
    appType: 'webApp'
    WebAppName: $(AppName)
    deployToSlotOrASE: true
    ResourceGroupName: $(ResourceGroupName)
    SlotName: 'production'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
    RemoveAdditionalFilesFlag: true
    ExcludeFilesFromAppDataFlag: false
    JSONFiles: 'appsettings.json'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

- task: VSTest@2
  displayName: "Run xUnit integrationTests tests"
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\bin\$(BuildConfiguration)\**\Albelli.Assessment.WebApi.IntegrationTests.dll
      !**\obj\**
      !**\ref\**
      !**\xunit.runner.visualstudio.testadapter.dll
      !**\xunit.runner.visualstudio.dotnetcore.testadapter.dll
    searchFolder: '$(System.DefaultWorkingDirectory)'